// Regenerates src/font-data.ts from public/fonts/Inter-Black.woff2.
//
// The font is inlined as a data: URL rather than fetched from public/ at render
// time. A render opens several browser tabs that all pull video and stills from
// the same local static server; the font request can end up queued behind them
// and blow past Remotion's 28s delayRender timeout, which kills the render with
// "A delayRender() Loading font ... was called but not cleared". Inlining makes
// the font available without any network round trip.
//
// Run with: npm run font:build
import { readFileSync, writeFileSync } from 'node:fs';

const source = new URL('../public/fonts/Inter-Black.woff2', import.meta.url);
const target = new URL('../src/font-data.ts', import.meta.url);

const base64 = readFileSync(source).toString('base64');

writeFileSync(
  target,
  `// GENERATED by scripts/build-font.mjs — do not edit by hand.
// Inter Black (900), latin subset. SIL OFL 1.1, see public/fonts/OFL.txt.
export const INTER_BLACK_WOFF2 =
  'data:font/woff2;base64,${base64}';
`,
);

console.log(`wrote src/font-data.ts (${base64.length} chars of base64)`);
